# Generated by Django 5.2 on 2025-05-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_site', '0002_delete_eval_project_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='score',
        ),
    ]
