# Generated by Django 5.2 on 2025-05-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_site', '0004_projectevaluation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectEvaluation',
            new_name='Score',
        ),
    ]
