# Generated by Django 5.2 on 2025-05-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_site', '0005_rename_projectevaluation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.TextField(default='기본 설명'),
        ),
    ]
