# Generated by Django 5.2 on 2025-05-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_site', '0006_project_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
